name: women_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/download.jpeg
    - assets/section1.jpeg
    - assets/section2.jpeg
    - assets/section3.jpeg
    # - assets/section4.jpg
    - assets/education2.jpg
    - assets/education3.jpg
    - assets/education4.jpeg
    - assets/tech2.jpg
    - assets/tech3.jpg
    - assets/tech4.jpeg
    - assets/sport1.jpg
    - assets/sport3.jpg
    - assets/sport3.jpg
    - assets/sport4.jpg
    - assets/culture2.jpg
    - assets/culture2.jpg
    - assets/culture4.jpg
